#!/bin/bash

#--------------------------------------------------------------------------#

# Anume Tool Made By Adkali [ v1.1 ]
# You can modify this tool as you wish
# Make it easy for yourself while making enumeration ( THM, HTB, etc.)
# Have Fun While You Can

#--------------------------------------------------------------------------#



# --- > Just Define The Script Colors To Make It Easy For Me ... //

Red="\e[31m"
Yellow="\e[105m"
GR="\e[92m"
Magenta="\e[95m"
EndColor="\e[0m"
bold=$(tput bold)

# --- > Intro Before The Code Starts ... //
 sleep 0.5
echo -e "\n{+}${bold}Run inside a compromised machine."
 sleep 0.5
echo -e "${Yellow}{+}${bold}Choose from a different kinds of options.${EndColor}"
 sleep 0.5
echo -e "{+}${bold}${GR}Use This Tool Wisely, And Only For Education Purpose Only.${EndColor}"
 sleep 0.5

#  -- > CODE STARTS NOW
    echo '''
    |  _____  |A
    | |\ ___| | D
    | | |   | | K
    | | |___| | A
    \ | |____\| L
     \|_________I 
     '''

options=("Detect Passwords/Usernames/Files/Anything Suspicious"
	"Find Setuid Files"
	"Show PATH variable"
	"Detect Sudo Version"
	"Find Sys Information"
	"Look for Private-Keys"
	"Running Proc's"
	"Exit")

# Function to display menu
ListToChoose(){
echo -e "\nPlease choose an option:"
for i in ${!options[@]}; do
    echo "$((i+1)) ${options[i]}"
done
}

# LOOP, LOOP, LOOP, LOOP
while true; do
    ListToChoose
    read -p "Qeury the number please: " Number

    # User input validation
    if ! [[ $Number =~ ^[0-9]+$ ]]; then
        echo -e "Wrong input!\nOnly numbers.."
        continue
    fi
    if (( Number < 1 || Number > ${#options[@]} )); then
        echo -e "Invalid number!\nPlease choose a number from the list."
        continue
    fi


    case $Number in
        1)
            echo -e "\n${Yellow}Suspicious files in the /etc directory?${EndColor}\n"
            sleep 2
            find /etc -writable -type f 2>/dev/null & find /etc -writable -type d 2>/dev/null
            sleep 2
            echo -e "\n${Yellow}Readable files in the /etc directory?${EndColor}\n"
            sleep 2
            find /etc -readable -type f 2>/dev/null
            sleep 2
            echo -e "\n${Yellow}Searching for writable files in the root directory...${EndColor}\n"
            sleep 2
            find / -type f -writable 2>/dev/null
            sleep 2
            echo -e "\n${Yellow}Setuid files in the root directory...${EndColor}\n"
            sleep 2
            find / -perm -4000 2>/dev/null
            sleep 2
            echo -e "\n${Yellow}Any passwords OR usernames files in the home directory?${EndColor}\n"
            sleep 2
            grep -rnw '/home' -e 'password' -e 'Password'
            sleep 2
            grep -rnw '/home' -e 'username' -e 'Username'
            sleep 2
            echo -e "\n${Yellow}Sensitive files in the /var/mail directory?${EndColor}\n"
            sleep 2
            ls -lha /var/mail
            sleep 2
            echo -e "\n${Yellow}Passwords in the user's history files?${EndColor}\n"
            sleep 2
            echo -e "\n${Yellow}Reading 'bash_history' if it exists...${EndColor}\n"
            cat ~/.bash_history 2>/dev/null
            sleep 2
            echo -e "\n${Yellow}Reading 'zsh_history' if it exists...${EndColor}\n"
            cat ~/.zsh_history 2>/dev/null
            ;;
        2)
            echo -e "\n${Yellow}Searching for setuid files in the root directory...${EndColor}\n"
            sleep 2
            find / -perm -user root -exec ls -ldb {} \; 2>/dev/null
            sleep 2
            echo -e "\n${Yellow}Searching for setuid files using another command...${EndColor}\n"
            sleep 2
            find / -perm -4000 2>/dev/null
            ;;
        3)
            echo $PATH
            ;;
        4)
            echo -e "\n${Yellow}Checking sudo version...${EndColor}\n"
            sleep 2
            sudo -V | grep "Sudo ver"
            sleep 2
            echo -e "\n${Yellow}Are You Authorized To Run Something As Root User/NO PASSWD?${EndColor}\n"
            sleep 2
            sudo -l
            ;;
        5)
            echo -e "\n${Yellow}Displaying system information...${EndColor}\n"
            sleep 2
            lsb_release -a
            sleep 2
            uname -a
            sleep 2
            echo -e "\n${Yellow}Searching inside env...${EndColor}\n"
            env | grep -i path
            sleep 1
			env | grep -i python
			sleep 1
			env | grep -i ^H
			sleep 1
			env | grep -i PATH$
			sleep 1
			env | grep -E 'PATH|Path|path'
			sleep 1
			env | grep -in path
			sleep 1
			env | grep -in path | nl -v 0
			sleep 1
			env | grep --color=auto -i path
			sleep 1
			env | grep -io path=*
			sleep 1
			env | grep -oE 'path=[^ ]+'



            ;;
        6)
            echo -e "\n${Yellow}Searching for private keys...${EndColor}\n"
            sleep 2
            find / -name "id_rsa*" -o -name "id_dsa*" 2>/dev/null
            ;;
        7)
			echo -e "\n${Yellow}Showing Running Proccess...${EndColor}\n"
  			sleep 2.5
  			ps -aux
  			sleep 2.5
			echo -e "\n${Yellow}Anything Running By Root User? Checking...${EndColor}\n"
  			sleep 2.5
  			ps -ef | grep root
  			sleep 2.5
  			echo -e "\n${Yellow}Any Cronjobs?${EndColor}\n"
  			sleep 2.5
  			ls -la /etc/cron.*
  			;;

        8)
            exit
            ;;
    esac
done
